source: .
destination: ./_site
layouts: ./_layouts
include: ['.htaccess']
exclude: []

permalink: /:year/:month/:title.html
author: fyears
title: Fleeting Years
tagline: "Time goes."
description: Time goes.
url: http://www.fyears.org
baseurl: 
signoff: fyears
disqus_shortname: fyears
google_analytics:

markdown: redcarpet
lsi: false

redcarpet:
  extensions:
    - with_toc_data
    - hard_wrap
    - no_intra_emphasis
    - tables
    - fenced_code_blocks
    - autolink

paginate: 10

gems:
  - jemoji
  - jekyll-sitemap
  - jekyll-redirect-from

prose:
  rooturl: ""
  media: 'uploads'
  metadata:
    _posts:
      - name: "layout"
        field:
          element: "hidden"
          value: "post"
      - name: "title"
        field:
          element: "text"
          label: "Title"
          value: ""
          type: "text"
      - name: "categories"
        field:
          element: "multiselect"
          label: "Post Category"
          placeholder: "Create or choose"
          alterable: true
      - name: "tags"
        field:
          element: "multiselect"
          label: "Add Tags"
          placeholder: "Choose Tags"
          alterable: true
