markdown: redcarpet
permalink: /:year/:month/:title/
author: fyears
name: Fleeting Years
description: Fleeting years bright the life. // 流光溢彩，年华转逝。
url: http://www.fyears.org

prose:
  rooturl: ""
  metadata: 
    "_posts": |
      published: false
      layout: post
      title: ""
      abstract: ""
      description: ""
      categories:
      - 
      tags:
      - 
      - 