source: .
destination: ./_site
layouts_dir: ./_layouts
include: ['.htaccess']
exclude: []

permalink: /:year/:month/:title.html
author: fyears
title: Fleeting Years
tagline: "Time goes."
description: Time goes.
url: http://www.fyears.org
baseurl:
disqus_shortname: fyears
google_analytics:

markdown: kramdown
highlighter: rouge
lsi: false

kramdown:
  input:          GFM
  auto_ids:       true
  footnote_nr:    1
  entity_output:  as_char
  toc_levels:     1..6
  smart_quotes:   lsquo,rsquo,ldquo,rdquo
  enable_coderay: false
  hard_wrap:      true

paginate: 10

gems:
  - jemoji
  - jekyll-sitemap
  - jekyll-redirect-from
  - jekyll-paginate

gist:
  nonscript: false

repository: fyears/fyears.github.com
