source: .
destination: ./_site
layouts_dir: ./_layouts
include: ['.htaccess']
exclude: []

permalink: /:year/:month/:title.html
author: fyears
title: Fleeting Years
tagline: "Time goes."
description: Time goes.
url: http://www.fyears.org
baseurl: 
signoff: fyears
disqus_shortname: fyears
google_analytics:

markdown: kramdown
highlighter: rouge
lsi: false

redcarpet:
  extensions:
    - with_toc_data
    - hard_wrap
    - no_intra_emphasis
    - tables
    - fenced_code_blocks
    - autolink

kramdown:
  input:          GFM
  auto_ids:       true
  footnote_nr:    1
  entity_output:  as_char
  toc_levels:     1..6
  smart_quotes:   lsquo,rsquo,ldquo,rdquo
  enable_coderay: false
  hard_wrap:      true

paginate: 10

gems:
  - jemoji
  - jekyll-sitemap
  - jekyll-redirect-from
  - jekyll-paginate

prose:
  rooturl: ""
  media: 'uploads'
  metadata:
    _posts:
      - name: "layout"
        field:
          element: "hidden"
          value: "post"
      - name: "title"
        field:
          element: "text"
          label: "Title"
          value: ""
          type: "text"
      - name: "categories"
        field:
          element: "multiselect"
          label: "Post Category"
          placeholder: "Create or choose"
          alterable: true
      - name: "tags"
        field:
          element: "multiselect"
          label: "Add Tags"
          placeholder: "Choose Tags"
          alterable: true
