source: .
destination: ./_site
layouts: ./_layouts
include: ['.htaccess']
exclude: []

permalink: /:year/:month/:title/
author: fyears
title: Fleeting Years
description: Fleeting years bright the life. // 流光溢彩，年华转逝。
url: http://www.fyears.org
baseurl: 
signoff: fyears
disqus_shortname: fyears
google_analytics:

links:
  - name:         Blog
    url:          /
  - name:         About
    url:          /about/
  - name:         Categories
    url:          /categories/
  - name:         Tags
    url:          /tags/
  - name:         Links
    url:          /links/
  - name:         Feed
    url:          /feed/

markdown: redcarpet
safe: true
lsi: false

prose:
  rooturl: ""
  metadata: 
    "_posts": |
      published: false
      layout: post
      title: ""
      abstract: ""
      description: ""
      categories:
      - 
      tags:
      - 
      - 